version: 2
updates:
  # Root package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
    labels:
      - "dependencies"
      - "npm"
  
  # Common package
  - package-ecosystem: "npm"
    directory: "/packages/common"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "npm"
  
  # Converter package
  - package-ecosystem: "npm"
    directory: "/packages/converter"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "npm"
  
  # Generator package
  - package-ecosystem: "npm"
    directory: "/packages/generator"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "npm"
  
  # Manipulator package
  - package-ecosystem: "npm"
    directory: "/packages/manipulator"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "npm"
  
  # Schemas package
  - package-ecosystem: "npm"
    directory: "/packages/schemas"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "npm"
  
  # UI package
  - package-ecosystem: "npm"
    directory: "/packages/ui"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "npm"
  
  # Playground
  - package-ecosystem: "npm"
    directory: "/playground"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "npm"
  
  # Website
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "npm"
