# .github/workflows/publish-release.yml
name: Publish Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpixman-1-dev libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Install dependencies
        run: npm ci

      - name: Set NPM version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          npm version $VERSION --no-git-tag-version --workspaces

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
        env:
          CI: true

      - name: Determine NPM tag
        run: ./scripts/determine-npm-tag.sh

      - name: Publish to NPM
        run: npm publish --workspaces --access public --tag ${{ env.NPM_TAG }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  playground-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpixman-1-dev libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Install dependencies and build project
        run: |
          npm ci
          npm run build

      - name: Run playground tests
        run: |
          cd playground
          npm install
          npm run build
          npm run test
        env:
          CI: true
