name: Testing

on: [pull_request]

jobs:
  pdfme-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpixman-1-dev libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - run: npm install
      - run: npm run build
      - run: npm run lint
      - run: npm run test
        env:
          CI: true

  playground-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpixman-1-dev libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - name: Install dependencies and build project
        run: |
          npm install
          npm run build
      - name: Run playground tests
        run: |
          cd playground
          npm install
          npm run lint
          npm run build
          npm run test
        env:
          CI: true
