name: Testing

on:
  pull_request:
  issue_comment:
    types: [created]

jobs:
  pdfme-test:
    if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/retest'))
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Get PR head ref (if triggered by /retest comment)
        if: github.event_name == 'issue_comment'
        id: pr
        uses: actions/github-script@v6
        with:
          script: |
            const prUrl = context.payload.issue.pull_request.url;
            const prNumber = prUrl.split('/').pop();
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: Number(prNumber)
            });
            core.setOutput('ref', pr.head.ref);
      
      - name: Set ref for PR
        id: set-ref
        run: |
          if [ "${{ github.event_name }}" == "issue_comment" ]; then
            echo "ref=${{ steps.pr.outputs.ref }}" >> $GITHUB_OUTPUT
          else
            echo "ref=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
          fi
      
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.set-ref.outputs.ref }}
          fetch-depth: 0
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - run: npm install
      - run: npm run build
      - run: npm run test
        env:
          CI: true

  playground-test:
    if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/retest'))
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Get PR head ref (if triggered by /retest comment)
        if: github.event_name == 'issue_comment'
        id: pr
        uses: actions/github-script@v6
        with:
          script: |
            const prUrl = context.payload.issue.pull_request.url;
            const prNumber = prUrl.split('/').pop();
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: Number(prNumber)
            });
            core.setOutput('ref', pr.head.ref);
      
      - name: Set ref for PR
        id: set-ref
        run: |
          if [ "${{ github.event_name }}" == "issue_comment" ]; then
            echo "ref=${{ steps.pr.outputs.ref }}" >> $GITHUB_OUTPUT
          else
            echo "ref=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
          fi
      
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.set-ref.outputs.ref }}
          fetch-depth: 0
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies and build project
        run: |
          npm install
          npm run build
          
      - name: Run playground tests
        run: |
          cd playground
          npm install
          npm run test
        env:
          CI: true
